### ISSUE TITLE
Heap Space Error on CSV Export

### ISSUE THREAD

**Issue by jduke99** [OHDSI/StudyProtocols#1]
Running Oracle.  First two exports work fine:

> extractAndWriteToFile(conn, "person_count", resultsSchema, sourceName, "T2DM", dbms)
> extractAndWriteToFile(conn, "person_count_year", resultsSchema, sourceName, "T2DM", dbms)

Last two exports throw an error:

> extractAndWriteToFile(conn, "seq_count", resultsSchema, sourceName, "T2DM", dbms)
> Error executing SQL: Error in .jcall(rp, "I", "fetch", stride): java.lang.OutOfMemoryError: Java heap space
> Error in value[[3L]](cond) : no loop for break/next, jumping to top level
> 
> extractAndWriteToFile(conn, "seq_count_year", resultsSchema, sourceName, "T2DM", dbms)
> Error executing SQL: Error in .jcall(rp, "I", "fetch", stride): java.lang.OutOfMemoryError: Java heap space

Any ideas?

**Comment by schuemie** [comment]
Sorry about that! I had not figured the exported tables would be so big they would not fit in Java's memory. 

Please see the java_heap branch for a possible solution: using `dbGetQuery.ffdf()` instead of `querySql()` (both in the DatabaseConnector package). This new function will load the data into an ffdf object, our current preferred solution for storing (very) large data objects.
